### ISSUE TITLE
Running CESAR-P fails after default installation

### ISSUE THREAD

**Issue by LeonieFierz** [hues-platform/cesar-p-core#1]
When installing CESAR-P in a Python environment with Python Version 3.8.9 the example provided in cesar-p-usage-examples project will fail with below error somewhere in pandas.

**Solution**: update pandas to version 1.0.5 with 
**pip install pandas==1.0.5**

Stacktrace:

_Traceback (most recent call last):
  File "C:\xxx\Local\Programs\Python\Python38\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\xxx\Local\Temp\venv-cesar-p\lib\site-packages\cesarp\manager\processing_steps.py", line 87, in create_bldg_models_batch_no_exception        
    bldg_models_factory = BldgModelFactory(pint.get_application_registry(), config, sia_params_gen_lock)
  File "C:\xxx\Local\Temp\venv-cesar-p\lib\site-packages\cesarp\manager\BldgModelFactory.py", line 91, in __init__
    self._geometry_builder_factory: GeometryBuilderFactoryProtocol = self.__create_geometry_builder_factory()
  File "C:\xxx\Local\Temp\venv-cesar-p\lib\site-packages\cesarp\manager\BldgModelFactory.py", line 109, in __create_geometry_builder_factory
    return GeometryBuilderFactory(flat_site_vertices_list, ureg=self._unit_reg, custom_config=self._custom_config)
  File "C:\xxx\Local\Temp\venv-cesar-p\lib\site-packages\cesarp\geometry\GeometryBuilderFactory.py", line 32, in __init__
    self._site_bldgs = vertices_basics.convert_flat_site_vertices_to_per_bldg_footprint(flat_site_vertices_list)
  File "C:\xxx\Local\Temp\venv-cesar-p\lib\site-packages\cesarp\geometry\vertices_basics.py", line 127, in convert_flat_site_vertices_to_per_bldg_footprint
    all_buildings = pd.DataFrame(columns=["gis_fid", "height", "footprint_shape"])
  File "C:\xxx\Local\Temp\venv-cesar-p\lib\site-packages\pandas\core\frame.py", line 411, in __init__
    mgr = init_dict(data, index, columns, dtype=dtype)
  File "C:\xxx\Local\Temp\venv-cesar-p\lib\site-packages\pandas\core\internals\construction.py", line 242, in init_dict
    val = construct_1d_arraylike_from_scalar(np.nan, len(index), nan_dtype)
  File "C:\xxx\Local\Temp\venv-cesar-p\lib\site-packages\pandas\core\dtypes\cast.py", line 1221, in construct_1d_arraylike_from_scalar
    dtype = dtype.dtype
AttributeError: type object 'object' has no attribute 'dtype'_

**Comment by LeonieFierz** [comment]
Versions of all dependencies were updated with cesar-p version 2.0.0, which solves above problem (we use now pandas 1.3)
